### PR TITLE
Improvement of JsTree 3 themes and plugins support

### PR DESCRIPTION
**Pull request by flofourcade**
- add support for other plugins provided by jstree (search, sort, massload, ... ) via a new `plugins` attribute in `<sjt:tree />`.
It expects an JSON formatted string with key -> plugin name and value -> the config object for the plugin
(eg `plugins="{search:{ajax:false}}` to enable jstree search plugin without AJAX.)
Be careful, you can override here configuration of plugins already defined with other tag attributes (checkbox, contextmenu...). This behaviour can be easily altered by a little change in jquery.tree.struts2.js

- add support for JsTree 3 theme "Variant" and "Responsive".
Some JsTree 3 themes now support variant (eg "large") and responsive mode.
You can configure this with the new `jstreethemeVariant="variant_name"` and `jstreethemeResponsive="boolean"` attributes.

### CODE REVIEW

**Comment by jogep** [comment]
@flofourcade thank you for this valuable contribution! It is merged now in the 4.0.1 branch.

**Comment by jogep** [comment]
Does this search feature work for you? When I click on search nothing happens.

**Comment by flofourcade** [comment]
Yes it works. On the non AJAX example, if you type twitter, the node Struts @ Twitter must be highlighted and all his parent nodes opened.
Same behaviour expected for the AJAX search feature.
Maybe I have missed something in my commit. Are there errors in the browser console ?

**Comment by flofourcade** [comment]
Search works but I have a JS error, even if it does not block the search for me.
 I used `<sj:submit />` without form instead of `<sj:a />`, which would be cleaner. 
Have to replace 
```html
<sj:submit value="Search" button="true" 
    onclick="$('#treeSearch').jstree('search', $('#searchField').val())" />
```
by
```html
<sj:a onclick="$('#treeSearch').jstree('search', $('#searchField').val())" button="true" >Search</sj:a>
```
in tree.jsp and tree-json.jsp. 
Over used Copy / Paste !

**Comment by jogep** [comment]
What you think about using two new attributes on the jstree component?

searchTopic = Define a topic which triggers the search
searchElementId = ID of the search element

Then we don't need a onClick with code we just need to define a topic which can be published by any other element.

**Comment by flofourcade** [comment]
Yes, at first I wanted to do thing this way But there are a lot of other plugins (sort,massload,, )and so I had to add a lot of new attributes to handle the config of each plugin. So I choosed to use only one "generic" attribute for all plugins., at first.
If you want I'll add searchTopic and searchElementId and we'll see later if we add attribute for other plugins.

**Comment by flofourcade** [comment]
@jogep 
added searchTopic searchElementId, and onSearchCompleteTopics., and updated the showcase.
I refs this PR in my commit. Should I open a new PR or can you merge from this one ?

**Comment by jogep** [comment]
Sorry, but it looks like a new PR is necessary.

**Comment by flofourcade** [comment]
OK. The search plugin has also "clear_search" method and event. To be complete on the search plugin, I'll add it to tree tag then submit a new PR.

**Pull request merged**
