### PR TITLE
Refactored adding ognl evaluated parameter with null check into a method

### PR DESCRIPTION
**Pull request by sdutry**
This is a suggestion refactoring to reduce the code in the following form:

```java
if (x != null) {
    addParameter("x", findString(x));
}
```
or
```java
if (x != null) {
    addParameter("x", findValue(x, type));
}
``` 
@jogep,
Seeing as: 
- this affects a large amount of files
- I'm not sure you would agree with this change 

I don't want to be the one doing the actualy merge.

If you don't agree with the pull request, then feel free to reject and just close it and let me know.

### CODE REVIEW

**Comment by lukaszlenart** [comment]
What's wrong with current approach? `findValue()` should be able to handle nulls and will return `null` in such case.

**Comment by sdutry** [comment]
@lukaszlenart 
I didn't actualy change any of the logic, i just extracted a method that handled the nullcheck.
From what you tell me, it looks like the null check is redundant by itself.

I overlooked what the underlying code was actualy doing.

- The `findValue()` method (and therefore also the `findString()` method) actualy handle `null` arguments by returning `null`
- the `addParameter()` method will try to remove the key from the Map when the when the value is `null`

So code blocks like: 
```java
if (x != null) {
    addParameter("x", findString(x));
}
```
or
```java
if (x != null) {
    addParameter("x", findValue(x, type));
}
```
could simply be replaced by the following? :
```java
addParameter("x", findString(x));
```
or
```java
addParameter("x", findValue(x, type));
```
methods that seem to be handling it in the underlying struts code:
* `com.opensymphony.xwork2.ognl.OgnlValueStacktry`
  * `tryFindValueWhenExpressionIsNotNull`
* `org.apache.struts2.util.ComponentUtils`
  * `isExpression`
  * `containsExpression`

But considering that the components from the core struts library themselves still hold these null checks also, i'm guessing they're there to improve performance?

**Comment by lukaszlenart** [comment]
So this whole change is about improving performance? If so I would do it in the Struts 2 Core, it should be easier to do it than here :)

**Comment by sdutry** [comment]
@lukaszlenart 
No, it's not about improving performance here.

It was just to remove the following returning lines all over the code:
- check variable not null.
- find ognl evaluated value for variable
- add it to the parameter map.

I just replaced those with a single method call.

But i think i'll just close the pull request alltogether and think things through a bit more first.
This discussion has given me some more insight in the whole underlying OGNL evaluation.

**Pull request closed without merging**
