### PR TITLE
Old jQuery Libary 2.2.4 has security issues so need to be upgraded to…

### PR DESCRIPTION
**Pull request by lalumastan**
… jQuery 3.5.0+ preferably jQuery 3.6.0 #194

### CODE REVIEW

**Comment by jpcrowe** [comment]
Would really love to see this pull request considered.  Otherwise this plugin is unusable in any web app that needs any level of security.

**Comment by lalumastan** [comment]
> 
> 
> Would really love to see this pull request considered. Otherwise this plugin is unusable in any web app that needs any level of security.

**Comment by marwin1991** [comment]
Any progress?

**Comment by marwin1991** [comment]
After migrating to 3.6.0 of jquery I had a problem with mimification, so it can be alos here a good idea to start sovling problems.

**Comment by tobiasstadler** [comment]
@lukaszlenart Would you mind having a look?

**Comment by lukaszlenart** [comment]
I'm not a jQuery expert and I have no experience with the plugin either. Let me set up some CI first

**Comment by lukaszlenart** [comment]
It won't be that easy - a lot of tests are failing :(

**Comment by sdutry** [comment]
part of the upcoming 5.0.0 release

see issue #210 and PR #220

Further updates and validations and tests will be done part of the [5.0.0 milestone](https://github.com/struts-community-plugins/struts2-jquery/milestone/6) and [5.0.x project](https://github.com/orgs/struts-community-plugins/projects/1) before release

**Pull request closed without merging**
