### PR TITLE
Includes nonce attribute in <script> tags

### LINKED ISSUE #142: Struts2 jquery plugin doesn't work with CSP script-src secure
I'm trying to use struts2-jquery-plugin but i can't . The reason is my content-secure-policy header against Cross Site Scripting (XSS) attacks... How can i solve it without use 'unsafe-inline' mode in script-src field?

Thanks a lot.

### PR DESCRIPTION
**Pull request by lukaszlenart**
Closes #142
~~Depends on https://github.com/apache/struts/pull/629~~

### CODE REVIEW

**Comment by lukaszlenart** [comment]
I must use `<s:script/>` tag to have `nonce`

**Comment by TheFergus** [comment]
@lukaszlenart Hi, for <s: script><s:/script>, if the src of the tags needs variables, what should I do? 
    `<s:script src="${myUrl}"></s:script>`

**Comment by lukaszlenart** [comment]
> @lukaszlenart Hi, for <s: script><s:/script>, if the src of the tags needs variables, what should I do? `<s:script src="${myUrl}"></s:script>`

The simplest way is to use `<s:url/>`

```
<s:url var="js" value="js/html5.js"/>
<s:script src="%{js}"/>
```

**Comment by lukaszlenart** [comment]
@jogep or @sdutry could you review/approve this PR? It would be good to release a new version of the JQuery plugin as this will allow to fix an issue in the Bootstrap plugin as well.

**Review by sdutry — APPROVED** [review]
LGTM

**Comment by jogep** [comment]
@lukaszlenart just spended a minute to test if we are ready to release. But the grid showcase failed to load and it needs some investigations.

`Caused by: freemarker.core.ParseException: Syntax error in template "template/jquery/grid-close.ftl" in line 355, column 1:
Encountered "</@s.script>", but was expecting one of:
`

**Comment by lukaszlenart** [comment]
Ok, I will fix that

**Pull request merged**
