### PR TITLE
issue #308 make id field dynamic again

### LINKED ISSUE #308: @id with dynamic variable doesn't work anymore
Since release 5.0.0 we can't have multiple dialog

```
<%@ taglib prefix="sj" uri="/struts-jquery-tags" %>

<s:iterator value="myBeanList" var="rrSum" status="status">

  <sj:dialog id="dialog%{#status.index}" href="%{ajaxURL}" title="Testing %{#status.index}" />
  <sj:a openDialog="dialog%{#status.index}"><s:property value="#rrSum.rid" /></sj:a>

 </s:iterator>
```
**title** param will be correct --> Testing 1, Testing 3 etc...
but **id** will be dialog%{#status.index} whereas dialog1, dialog2 etc...

what did i miss? Is it a real bug ? or new feature ? :)

### PR DESCRIPTION
**Pull request by sdutry**
fixes #308

### CODE REVIEW

**Comment by sdutry** [comment]
looking into changing it back and using escapedId as you suggested

**Comment by sdutry** [comment]
this will mean a change in all templates where id is used

**Comment by sdutry** [comment]
@lukaszlenart am i correct in concluding that i'll have to add the escaped_id parameter myself using the escape function and then in the ftl templates use the escapedId parameter?

**Comment by lukaszlenart** [comment]
> @lukaszlenart am i correct in concluding that i'll have to add the escaped_id parameter myself using the escape function and then in the ftl templates use the escapedId parameter?

I think you can just omit the `else` statement like this:

```java
protected void addGeneratedIdParam(String prefix) {
    if (StringUtils.isBlank(this.id)) {
        // resolves Math.abs(Integer.MIN_VALUE) issue reported by FindBugs
        // http://findbugs.sourceforge.net/bugDescriptions.html#RV_ABSOLUTE_VALUE_OF_RANDOM_INT
        int nextInt = RANDOM.nextInt();
        nextInt = nextInt == Integer.MIN_VALUE ? Integer.MAX_VALUE : Math.abs(nextInt);
        this.id = prefix + String.valueOf(nextInt);
        addParameter(PARAM_ID, this.id);
        addParameter("escapedId", this.id);
    }
}
```
and then use `parameters.escapedId` in the template. 

Yet I think such change is good for a minor release not just a bug fix :)

**Review by lukaszlenart — APPROVED** [review]
LGTM 👍

**Comment by lukaszlenart** [comment]
I prepared my change also addressing some deprecation warnings #310

**Pull request closed without merging**
