### PR TITLE
- #40 - fixes handling of groupShowSummaryOnHide

### LINKED ISSUE #40: Grids groupShowSummaryOnHide="[true]" is not working
It seems that setting the groupShowSummaryOnHide="[true]" is not working and we face free maker exception

```
FreeMarker template error (HTML_DEBUG mode; use RETHROW in production!)


For "#if" condition: Expected a boolean, but this evaluated to a string+extended_hash (String wrapped into f.e.b.StringModel):
==> parameters.groupShowSummaryOnHide?default(false)  [in template "template/jquery/grid-close.ftl" at line 138, column 16]

----
FTL stack trace ("~" means nesting-related):
    - Failed at: #if parameters.groupShowSummaryOnHide...  [in template "template/jquery/grid-close.ftl" at line 138, column 11]
----

Java stack trace (for programmers):
----
freemarker.core.NonBooleanException: [... Exception message was already printed; see it above ...]
    at freemarker.core.Expression.modelToBoolean(Expression.java:136)
    at freemarker.core.Expression.evalToBoolean(Expression.java:119)
    at freemarker.core.Expression.evalToBoolean(Expression.java:110)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:46)
    at freemarker.core.Environment.visit(Environment.java:312)
    at freemarker.core.MixedContent.accept(MixedContent.java:62)
    at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
    at freemarker.core.Environment.visit(Environment.java:312)
    at freemarker.core.MixedContent.accept(MixedContent.java:62)
    at freemarker.core.Environment.visit(Environment.java:312)
    at freemarker.core.Environment.process(Environment.java:290)
    at freemarker.template.Template.process(Template.java:312)
    at org.apache.struts2.components.template.FreemarkerTemplateEngine.renderTemplate(FreemarkerTemplateEngine.java:158)


```

### PR DESCRIPTION
**Pull request by flofourcade**
Fixes #40 by making this param be evaluated as boolean by freemarker

### CODE REVIEW

**Comment by flofourcade** [comment]
We could follow Apache Java Coding style, and to help contributors, we could export these conventions into files that majors IDE (Eclipse, IDEA, ...) can import to autoconfigure their code format.

**Comment by sdutry** [comment]
@flofourcade 
That would be the original idea, except i can't realy find a general document.

Since this is a plugin for the struts project, i took a look at [https://struts.apache.org/releases.html#coding-conventions-and-guidelines](https://struts.apache.org/releases.html#coding-conventions-and-guidelines).
This refers to the oracle published code guidelines with a non-working link. I think it used to refer to [http://www.oracle.com/technetwork/java/codeconventions-150003.pdf](http://www.oracle.com/technetwork/java/codeconventions-150003.pdf)
This dates back to 1997 and therefore doesn't include many rules concerning more recent features.

I mostly stand by the first clarification in there: 

> First, “Observe the style of the original”. Resist the temptation to make stylistic changes for their own sake. But, if you must reformat code, commit style changes separately from code changes. Either change the style, commit, and then change the code, or vice-versa.

When i get around to it, i'll ask the struts team if they have configuration files for editors that can be used.

**Comment by flofourcade** [comment]
I found xml s for IDEA and Eclipse on Apache Maven project site. Their rules seem common to several  apache projects.[https://maven.apache.org/developers/conventions/code.html](url)

**Comment by sdutry** [comment]
@flofourcade from the first glance, there's still a huge discrepantie with those.
To just list a few (how they are in the struts project as opposed to these)
* opening braces are not on a new line
* no space before first argument
* no space after last argument
* throws statements don't get a seperate line

On a sidenote, i don't know a single code formatting xml that handles nested annotations in any reasonable way. (trust me, i've spent hours trying to configure that correctly)

From a personal work experience, we ended up selecting the blocks of code we wanted formatted and only used the formatter that way.

Personaly i stopped using formatters completely because more than half of the time it screws up something.

**Comment by flofourcade** [comment]
You're right, so if there's no better suitable solution,  the best is just not to use autoformatting features and just take care of using spaces instead of tabs for indentation.

**Review by jogep — COMMENTED** [review]
This review is hard to check because of the white space changes I cannot identify the changes.

**Comment by flofourcade** [comment]
@jogep. Sorry, I didn t disable my IDE autoformatting when I commited this. @sdutry pushed a commit that corrected formatting.

**Comment by flofourcade** [comment]
The only thing I change in this file is addParameterIfPresent(PARAM_GROUP_SHOW_SUMMARY_ON_HIDE, this.groupShowSummaryOnHide, Boolean.class);
to force a boolean eval in ftl template

**Pull request merged**
