### PR TITLE
Use already generated id

### PR DESCRIPTION
**Pull request by tobiasstadler**
Fixes using `%{...}` for grid id

### CODE REVIEW

**Comment by tobiasstadler** [comment]
@lukaszlenart Would you please have a look?

**Review by lukaszlenart — APPROVED** [review]
LGTM 👍

**Comment by tobiasstadler** [comment]
Thank You!

**Comment by tobiasstadler** [comment]
Will there be a new release (soon)?

**Comment by sdutry** [comment]
@tobiasstadler 
We're currently working on a new release for struts 6 which usus jquery 3.6 and updated libraries.

Seeing it's all new versions and a lot of updates need to happen, it's taking some time.

As soon as we're done going through all updates and have assured everything is working again, we'll be releasing a new version.

**Comment by tobiasstadler** [comment]
I am looking forward to it.Thank you for your effort.

**Pull request merged**
