### PR TITLE
Struts 2.5 support

### PR DESCRIPTION
**Pull request by flofourcade**
- fix jstree tag : replace `<#include "/${parameters.templateDir}/simple/div-close.ftl" />`  by `</div>` (s:div
suppressed in Struts 2.5)
- fix jstree theme loading for action url not in root context : use
$.scriptPath (not sure if it's the good way)
- fix missing require for scale and puff effects needing effect-size.js
- replace all "id" attributes removed in Struts 2.5 by "var" in s:set
and s:url tags, in JSPs and FTLs -> fix showcase and richtext editors
- different fixes making showcase app work
- fix onSuccess and onComplete topics for `<sjt:tree />` tag

### CODE REVIEW

**Comment by jogep** [comment]
Thank you for taking care about this.
The PR is merged now.

**Comment by flofourcade** [comment]
Hi! I got some ideas to improve the tree tag. Jstree 3 now supports responsive theme and theme variant. We could add some attributes to the tag to support these features. Also jstree 3 come with useful plugins like search,... It would be great to enable and configure these plugins from the tag. Having a look at the code, and I think it could be fast and easy to implement it.

**Comment by jogep** [comment]
@flofourcade sounds interesting. PR's are always welcome. ;-)

**Comment by flofourcade** [comment]
Work already done on my fork, I update the jstree showcase to give an example then I submit a PR.

**Pull request merged**
